name: Deploy Frontend to AWS Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install Amplify CLI
      run: |
        npm install -g @aws-amplify/cli

    - name: List directories
      run: |
        ls -la  

    - name: Navigate to frontend folder
      run: |
        cd frontend 
        ls -la 

    - name: Install dependencies
      run: |
        cd frontend  
        npm install --legacy-peer-deps

    - name: Build project
      run: |
        cd frontend
        npm run build