name: Deploy to AWS ECR

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push FRONTEND image
      run: |
        docker build -t $ECR_REPO_FRONTEND ./frontend
        docker tag $ECR_REPO_FRONTEND:latest $ECR_REPO_FRONTEND:latest
        docker push $ECR_REPO_FRONTEND:latest

    - name: Build and push BACKEND image
      run: |
        docker build -t $ECR_REPO_BACKEND ./backend
        docker tag $ECR_REPO_BACKEND:latest $ECR_REPO_BACKEND:latest
        docker push $ECR_REPO_BACKEND:latest
