name: Deploy Frontend to AWS Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigate to frontend folder
      run: cd frontend

    - name: Install dependencies
      run: |
        frontend/npm install

    - name: Build project
      run: |
        frontend/npm run build

    - name: Deploy to AWS Amplify
      run: |
        amplify publish